/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SearchResult {
  id: string
  distance: number
  metadata?: any
}
export interface GetResult {
  vector: Array<number>
  metadata?: any
}
export declare class VctrsDatabase {
  /**
   * Open or create a database.
   * If the database exists, dim and metric are auto-detected (pass null).
   * Optional: hnswM (default 16), efConstruction (default 200), quantize (default false).
   */
  constructor(path: string, dim?: number | undefined | null, metric?: string | undefined | null, hnswM?: number | undefined | null, efConstruction?: number | undefined | null, quantize?: boolean | undefined | null)
  add(id: string, vector: Array<number>, metadata?: any | undefined | null): void
  /** Add or update a vector. */
  upsert(id: string, vector: Array<number>, metadata?: any | undefined | null): void
  addMany(ids: Array<string>, vectors: Array<Array<number>>, metadatas?: Array<any | undefined | null> | undefined | null): void
  /**
   * Search for k nearest neighbors.
   * `whereFilter`: optional object like { field: "value" }, { field: { $ne: "value" } },
   * { field: { $in: ["a", "b"] } }, or { field: { $gt: 10, $lte: 20 } }
   */
  search(vector: Array<number>, k?: number | undefined | null, efSearch?: number | undefined | null, whereFilter?: any | undefined | null): Array<SearchResult>
  /**
   * Search multiple queries in parallel. Returns array of result arrays.
   * `whereFilter`: optional object like { field: "value" }, { field: { $ne: "value" } },
   * { field: { $in: ["a", "b"] } }, or { field: { $gt: 10, $lte: 20 } }
   */
  searchMany(vectors: Array<Array<number>>, k?: number | undefined | null, efSearch?: number | undefined | null, whereFilter?: any | undefined | null): Array<Array<SearchResult>>
  get(id: string): GetResult
  delete(id: string): boolean
  update(id: string, vector?: Array<number> | undefined | null, metadata?: any | undefined | null): void
  contains(id: string): boolean
  ids(): Array<string>
  save(): void
  /** Close the database and save to disk. */
  close(): void
  /** Get graph-level statistics for diagnostics. */
  stats(): {
    numVectors: number
    numDeleted: number
    numLayers: number
    avgDegreeLayer0: number
    maxDegreeLayer0: number
    minDegreeLayer0: number
    memoryVectorsBytes: number
    memoryGraphBytes: number
    memoryQuantizedBytes: number
    usesBruteForce: boolean
    usesQuantizedSearch: boolean
  }
  /** Rebuild the index with only live vectors, reclaiming deleted slots. */
  compact(): void
  /** Enable quantized search: uses SQ8 quantized vectors for faster HNSW traversal with full-precision re-ranking. */
  enableQuantizedSearch(): void
  /** Disable quantized search. */
  disableQuantizedSearch(): void
  /** Whether quantized search is currently enabled. */
  get quantizedSearch(): boolean
  /** Number of deleted slots that haven't been reclaimed. */
  get deletedCount(): number
  /** Total allocated slots (active + deleted). */
  get totalSlots(): number
  get length(): number
  get dim(): number
  get metric(): string
}
