/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single search result. */
export interface SearchResult {
  /** The unique string identifier of the matched vector. */
  id: string
  /**
   * Distance between the query and this vector.
   * Lower is more similar for cosine and euclidean metrics.
   */
  distance: number
  /** The metadata object attached to this vector, or undefined. */
  metadata?: Record<string, any>
}

/** A vector and its metadata, returned by `get()`. */
export interface GetResult {
  /** The stored embedding vector. */
  vector: Array<number>
  /** The metadata object attached to this vector, or undefined. */
  metadata?: Record<string, any>
}

/**
 * Metadata filter for search queries.
 *
 * Supports equality, operators, and compound filters:
 * - Equality: `{ field: "value" }`
 * - Not-equal: `{ field: { $ne: "value" } }`
 * - In-set: `{ field: { $in: ["a", "b"] } }`
 * - Numeric ranges: `{ field: { $gt: 10, $lte: 20 } }`
 * - Compound (AND): `{ f1: "v1", f2: { $gt: 5 } }`
 */
export type WhereFilter = Record<string, any>

/** Graph-level statistics returned by `stats()`. */
export interface VctrsStats {
  /** Number of active (non-deleted) vectors. */
  numVectors: number
  /** Number of deleted vectors not yet reclaimed. */
  numDeleted: number
  /** Number of HNSW layers. */
  numLayers: number
  /** Average degree (edges) on layer 0. */
  avgDegreeLayer0: number
  /** Maximum degree on layer 0. */
  maxDegreeLayer0: number
  /** Minimum degree on layer 0. */
  minDegreeLayer0: number
  /** Memory used by vector storage in bytes. */
  memoryVectorsBytes: number
  /** Memory used by graph structure in bytes. */
  memoryGraphBytes: number
  /** Memory used by quantized vectors in bytes (0 if not quantized). */
  memoryQuantizedBytes: number
  /** Whether brute-force search is being used (small datasets). */
  usesBruteForce: boolean
  /** Whether quantized HNSW traversal is enabled. */
  usesQuantizedSearch: boolean
}

/**
 * A persistent vector database backed by an HNSW index.
 *
 * Stores vectors with string IDs and optional JSON metadata.
 * Supports cosine, euclidean (L2), and dot-product distance metrics.
 * Uses memory-mapped I/O for fast loading and a write-ahead log for
 * crash safety.
 *
 * @example
 * ```typescript
 * // Create a new database
 * const db = new VctrsDatabase("./my_db", 384, "cosine");
 * db.add("doc1", embedding, { title: "Hello" });
 * const results = db.search(queryVector, 5);
 * db.save();
 *
 * // Open an existing database (auto-detects dim and metric)
 * const db2 = new VctrsDatabase("./my_db");
 * ```
 */
export declare class VctrsDatabase {
  /**
   * Open or create a database.
   *
   * When opening an existing database, `dim` and `metric` are
   * auto-detected — pass `null` or omit them.
   *
   * @param path - Directory path for the database files.
   * @param dim - Vector dimensionality (e.g. 384). Required for new databases.
   * @param metric - Distance metric: "cosine" (default), "euclidean"/"l2",
   *   or "dot"/"dot_product".
   * @param hnswM - Max edges per HNSW node (default 16). Higher improves
   *   recall at the cost of memory.
   * @param efConstruction - Build-time search width (default 200). Higher
   *   improves index quality at the cost of build time.
   * @param quantize - Enable SQ8 scalar quantization for faster search.
   * @throws If opening an existing database without `dim` and it doesn't exist,
   *   or if `metric` is invalid.
   */
  constructor(
    path: string,
    dim?: number | undefined | null,
    metric?: string | undefined | null,
    hnswM?: number | undefined | null,
    efConstruction?: number | undefined | null,
    quantize?: boolean | undefined | null,
  )

  /**
   * Add a vector with a unique string ID.
   *
   * @param id - Unique identifier. Throws if the ID already exists
   *   (use `upsert()` to insert-or-update).
   * @param vector - The embedding vector. Must match the database's
   *   dimensionality.
   * @param metadata - Optional JSON-serializable metadata object.
   * @throws If the ID already exists or dimension doesn't match.
   */
  add(id: string, vector: Array<number>, metadata?: Record<string, any> | undefined | null): void

  /**
   * Insert a vector, or update it if the ID already exists.
   *
   * Same as `add()` but overwrites existing entries instead of throwing.
   *
   * @throws If the vector dimension doesn't match.
   */
  upsert(id: string, vector: Array<number>, metadata?: Record<string, any> | undefined | null): void

  /**
   * Batch insert multiple vectors.
   *
   * @param ids - Array of unique identifiers.
   * @param vectors - Array of embedding vectors.
   * @param metadatas - Optional array of metadata objects.
   * @throws If any ID already exists, lengths mismatch, or dimensions don't match.
   */
  addMany(
    ids: Array<string>,
    vectors: Array<Array<number>>,
    metadatas?: Array<Record<string, any> | undefined | null> | undefined | null,
  ): void

  /**
   * Batch upsert — inserts new vectors, updates existing ones.
   *
   * More efficient than calling `upsert()` in a loop because new
   * vectors are batch-inserted together.
   *
   * @throws If lengths mismatch or dimensions don't match.
   */
  upsertMany(
    ids: Array<string>,
    vectors: Array<Array<number>>,
    metadatas?: Array<Record<string, any> | undefined | null> | undefined | null,
  ): void

  /**
   * Find the k nearest neighbors to a query vector.
   *
   * @param vector - The query embedding.
   * @param k - Number of results to return (default 10).
   * @param efSearch - HNSW search-time width. Higher improves recall.
   * @param whereFilter - Optional metadata filter. See {@link WhereFilter}.
   * @param maxDistance - Optional distance threshold — discard results
   *   beyond this distance.
   * @returns Array of SearchResult objects sorted by distance (ascending).
   * @throws If the vector dimension doesn't match.
   *
   * @example
   * ```typescript
   * // Basic search
   * const results = db.search(queryVec, 5);
   *
   * // With metadata filter
   * const results = db.search(queryVec, 10, null, { category: "science" });
   *
   * // With distance threshold
   * const results = db.search(queryVec, 10, null, null, 0.5);
   * ```
   */
  search(
    vector: Array<number>,
    k?: number | undefined | null,
    efSearch?: number | undefined | null,
    whereFilter?: WhereFilter | undefined | null,
    maxDistance?: number | undefined | null,
  ): Array<SearchResult>

  /**
   * Search multiple queries in parallel.
   *
   * Significantly faster than calling `search()` in a loop.
   *
   * @returns Array of result arrays, one per query.
   * @throws If any vector dimension doesn't match.
   */
  searchMany(
    vectors: Array<Array<number>>,
    k?: number | undefined | null,
    efSearch?: number | undefined | null,
    whereFilter?: WhereFilter | undefined | null,
    maxDistance?: number | undefined | null,
  ): Array<Array<SearchResult>>

  /**
   * Count vectors matching a filter, or all vectors if no filter.
   *
   * Uses the inverted metadata index for fast counting with equality
   * and `$in` filters.
   */
  count(whereFilter?: WhereFilter | undefined | null): number

  /**
   * Retrieve a vector and its metadata by ID.
   *
   * @throws If the ID is not found.
   */
  get(id: string): GetResult

  /**
   * Delete a vector by ID.
   *
   * The slot is marked as deleted but not reclaimed until `compact()`
   * is called.
   *
   * @returns `true` if found and deleted, `false` if not found.
   * @throws On internal errors (e.g. WAL write failure).
   */
  delete(id: string): boolean

  /**
   * Update a vector's embedding and/or metadata in-place.
   *
   * @param id - The vector's unique identifier.
   * @param vector - New embedding (or null to keep existing).
   * @param metadata - New metadata (or null to keep existing).
   * @throws If the ID is not found or the vector dimension doesn't match.
   */
  update(
    id: string,
    vector?: Array<number> | undefined | null,
    metadata?: Record<string, any> | undefined | null,
  ): void

  /** Check if a vector ID exists in the database. */
  contains(id: string): boolean

  /** Return an array of all vector IDs in the database. */
  ids(): Array<string>

  /**
   * Persist the database to disk.
   *
   * Writes the HNSW graph, metadata, and vectors, then truncates the
   * write-ahead log.
   *
   * @throws On I/O errors (e.g. disk full, permission denied).
   */
  save(): void

  /**
   * Close the database and save to disk. Alias for `save()`.
   *
   * @throws On I/O errors.
   */
  close(): void

  /** Get graph-level statistics for diagnostics. */
  stats(): VctrsStats

  /**
   * Rebuild the index with only live vectors, reclaiming deleted slots.
   * Call after many deletions to reduce memory and disk usage.
   *
   * @throws On internal errors.
   */
  compact(): void

  /**
   * Enable SQ8 quantized search for faster HNSW traversal.
   *
   * Quantized vectors use 4x less memory for distance comparisons
   * during graph traversal, with full-precision re-ranking of final
   * candidates.
   */
  enableQuantizedSearch(): void

  /** Disable quantized search and use full-precision vectors. */
  disableQuantizedSearch(): void

  /** Whether quantized search is currently enabled. */
  get quantizedSearch(): boolean

  /** Number of deleted slots not yet reclaimed by `compact()`. */
  get deletedCount(): number

  /** Total allocated slots (active + deleted). */
  get totalSlots(): number

  /** Number of active vectors in the database. */
  get length(): number

  /** The vector dimensionality of this database. */
  get dim(): number

  /** The distance metric: "cosine", "euclidean", or "dot_product". */
  get metric(): string

  // -- Async methods (return Promises, run on libuv thread pool) --

  /** Async version of `add()`. */
  addAsync(id: string, vector: Array<number>, metadata?: Record<string, any> | undefined | null): Promise<void>

  /** Async version of `upsert()`. */
  upsertAsync(id: string, vector: Array<number>, metadata?: Record<string, any> | undefined | null): Promise<void>

  /** Async version of `addMany()`. */
  addManyAsync(
    ids: Array<string>,
    vectors: Array<Array<number>>,
    metadatas?: Array<Record<string, any> | undefined | null> | undefined | null,
  ): Promise<void>

  /** Async version of `upsertMany()`. */
  upsertManyAsync(
    ids: Array<string>,
    vectors: Array<Array<number>>,
    metadatas?: Array<Record<string, any> | undefined | null> | undefined | null,
  ): Promise<void>

  /** Async version of `search()`. */
  searchAsync(
    vector: Array<number>,
    k?: number | undefined | null,
    efSearch?: number | undefined | null,
    whereFilter?: WhereFilter | undefined | null,
    maxDistance?: number | undefined | null,
  ): Promise<Array<SearchResult>>

  /** Async version of `searchMany()`. */
  searchManyAsync(
    vectors: Array<Array<number>>,
    k?: number | undefined | null,
    efSearch?: number | undefined | null,
    whereFilter?: WhereFilter | undefined | null,
    maxDistance?: number | undefined | null,
  ): Promise<Array<Array<SearchResult>>>

  /** Async version of `save()`. */
  saveAsync(): Promise<void>

  /** Async version of `delete()`. */
  deleteAsync(id: string): Promise<boolean>
}
